// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Funfik.Web.Areas.Default.Controllers
{
    public partial class LikeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LikeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LikeArticle()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LikeArticle);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DislikeArticle()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DislikeArticle);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LikeController Actions { get { return MVC.Default.Like; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Default";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Like";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Like";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string LikeArticle = "LikeArticle";
            public readonly string DislikeArticle = "DislikeArticle";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string LikeArticle = "LikeArticle";
            public const string DislikeArticle = "DislikeArticle";
        }


        static readonly ActionParamsClass_LikeArticle s_params_LikeArticle = new ActionParamsClass_LikeArticle();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LikeArticle LikeArticleParams { get { return s_params_LikeArticle; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LikeArticle
        {
            public readonly string articleId = "articleId";
        }
        static readonly ActionParamsClass_DislikeArticle s_params_DislikeArticle = new ActionParamsClass_DislikeArticle();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DislikeArticle DislikeArticleParams { get { return s_params_DislikeArticle; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DislikeArticle
        {
            public readonly string articleId = "articleId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LikeController : Funfik.Web.Areas.Default.Controllers.LikeController
    {
        public T4MVC_LikeController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void LikeArticleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int articleId);

        public override System.Web.Mvc.ActionResult LikeArticle(int articleId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LikeArticle);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "articleId", articleId);
            LikeArticleOverride(callInfo, articleId);
            return callInfo;
        }

        partial void DislikeArticleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int articleId);

        public override System.Web.Mvc.ActionResult DislikeArticle(int articleId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DislikeArticle);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "articleId", articleId);
            DislikeArticleOverride(callInfo, articleId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
