// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Funfik.Web.Areas.Default.Controllers
{
    public partial class ChapterController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ChapterController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ChapterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowChapter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowChapter);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ChapterController Actions { get { return MVC.Default.Chapter; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Default";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Chapter";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Chapter";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ShowChapter = "ShowChapter";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ShowChapter = "ShowChapter";
        }


        static readonly ActionParamsClass_ShowChapter s_params_ShowChapter = new ActionParamsClass_ShowChapter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowChapter ShowChapterParams { get { return s_params_ShowChapter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowChapter
        {
            public readonly string chapter = "chapter";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ShowChapterPartial = "_ShowChapterPartial";
            }
            public readonly string _ShowChapterPartial = "~/Areas/Default/Views/Chapter/_ShowChapterPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ChapterController : Funfik.Web.Areas.Default.Controllers.ChapterController
    {
        public T4MVC_ChapterController() : base(Dummy.Instance) { }

        partial void ShowChapterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Funfik.Core.Entities.Chapter chapter);

        public override System.Web.Mvc.ActionResult ShowChapter(Funfik.Core.Entities.Chapter chapter)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowChapter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chapter", chapter);
            ShowChapterOverride(callInfo, chapter);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
